# Generated by Django 3.2.4 on 2021-06-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='joined',
        ),
    ]
