# Generated by Django 3.2.4 on 2021-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210623_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
