# Generated by Django 3.2.4 on 2021-06-24 09:18

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.svg', upload_to=user_profile.models.upload_path),
        ),
    ]
